"use strict";

const PETAL = {
    count: 10,
    orbitSpeed: 2.4,
    radius: 7.5,
    subpetalRadius: 7.5
};

const PETAL_RARITY = {
    min: 0,
    max: 8
};

const PETAL_RARITY_SCALE = [
    0,    // rarity 0 Common
    3,    // rarity 1 Uncommon
    9,    // rarity 2
    27,   // rarity 3
    81,   // rarity 4
    243,  // rarity 5
    729,  // rarity 6
    2187, // rarity 7
    6561  // rarity 8
];

const PetalTypes = {
    basic: { id: "basic", label: "Basic", dmg: 10, maxHp: 10, reload: 2.0 },
    rose: { id: "rose", label: "Rose", dmg: 5, maxHp: 10, reload: 2.0, heal: 5, healCooldown: 0.5, radius: .75 },
    leaf: { id: "leaf", label: "Leaf", dmg: 16, maxHp: 13, reload: 1.8, hps: 2, radius: 1.15 },
    maple: { id: "maple", label: "Maple", dmg: 16, maxHp: 13, reload: 1.8, hps: 2, radius: 1.15, playerSpeed: 0.75, buffReload: 5, radius: 1.2 },
    rock: { id: "rock", label: "Rock", dmg: 5, maxHp: 15, reload: 3.0, radius: 1.1 },
    rice: { id: "rice", label: "Rice", dmg: 5, maxHp: 1, reload: 0.000001, radius: .55, },
    stinger: { id: "stinger", label: "Stinger", dmg: 100, maxHp: 5, reload: 5, radius: .55, multi: [1, 1, 1, 1, 1, 3, 5, 5, 6], clumps: true, splitMultiDamage: true, },
    sand: { id: "sand", label: "Sand", dmg: 5, maxHp: 1.25, reload: 1.5, radius: .5, multi: [4, 4, 4, 4, 4, 4, 4, 4, 4], clumps: true, splitMultiDamage: false, },
    poo: { id: "poo", label: "Poo", dmg: 1, maxHp: 8, reload: 4.0, aggroRangeMult: 0.10, unstackable: true },
    lentil: { id: "lentil", label: "Lentil", dmg: 12, maxHp: 15, reload: 4.0, petalAttractBonus: 0.007, radius: .45 },
    wing: { id: "wing", label: "Wing", dmg: 20, maxHp: 10, reload: 2.5 },
    faster: {
        id: "faster",
        label: "Faster",
        dmg: 8,
        maxHp: 10,
        reload: 2.0,

        // Adds to petal orbit speed while alive.
        // R0 = +25%, R1 = +30%, R2 = +35%, etc.
        petalSpeedBonus: 0.25,
        petalSpeedBonusPerRarity: 0.05,

        radius: 0.75,
        spinSpeed: 3.5
    },
    landmine: {
        id: "landmine",
        label: "Landmine",
        dmg: 100,
        maxHp: 10,
        reload: 2.5,
        isDroppable: true,
        explosionRadiusBase: 500,
        explosionRadiusScale: 1.2, radius: 1.15,
        multi: [1, 1, 2, 2, 3, 3, 4, 4, 5],
        clumps: true,
        splitMultiDamage: true,
        radius: 1.75,
    },
    light: {
        id: "light",
        label: "Light",
        dmg: 12,
        maxHp: 8,
        reload: 0.75,
        multi: [1, 1, 2, 2, 3, 3, 4, 4, 5],
        clumps: false,
        splitMultiDamage: true,
        radius: 0.75,
    },
    pollen: {
        id: "pollen",
        label: "Pollen",
        dmg: 38,
        maxHp: 8,
        reload: 0.75,
        isDroppable: true,
        multi: [1, 1, 2, 3, 3, 3, 3, 3, 5],
        clumps: false,
        splitMultiDamage: true,
        radius: 0.75,
    },
    missile: {
        id: "missile",
        label: "Missile",
        dmg: 35,
        maxHp: 2,
        reload: 1.5,
        isDroppable: true,
    },
    yinYang: {
        id: "yinYang",
        label: "Yin Yang",
        dmg: 10,
        maxHp: 10,
        reload: 2.5,
        reversePetalRotation: true
    },
    pincer: {
        id: "pincer",
        label: "Pincer",
        dmg: 7,
        maxHp: 12,
        reload: 2.5,
        slowAmount: 0.25,
        slowDuration: 2.0,
        slowDurationPerRarity: 0.35
    },
    sap: {
        id: "sap",
        label: "Sap",
        dmg: 5,
        maxHp: 5,
        reload: 1.5,
        slowAmount: 0.3,
        slowDuration: 1.75,
        slowDurationPerRarity: 0.25
    },
    sawblade: {
        id: "sawblade",
        label: "Sawblade",
        dmg: 40,
        maxHp: 25,
        reload: 2.0,
        radius: 2,
    },
    beetleEgg: {
        id: "beetleEgg",
        label: "Beetle Egg",
        dmg: 1,
        maxHp: Number.MIN_VALUE,
        reload: 1.0,
        deathSummonType: "beetle",
        deathSummonRarityOffset: -1,
        deathSummonFaction: "owner",
        deathSummonBehavior: "hostile"
    },
    antEgg: {
        id: "antEgg",
        label: "Eggs",
        dmg: 1,
        maxHp: Number.MIN_VALUE,
        reload: 1.0,
        multi: [4, 4, 4, 4, 4, 4, 4, 4, 4],
        clumps: false,
        splitMultiDamage: true,
        deathSummonType: "antGuard",
        deathSummonRarityOffset: -1,
        deathSummonFaction: "owner",
        deathSummonBehavior: "hostile"
    },
    hornetEgg: {
        id: "hornetEgg",
        label: "Eggs",
        dmg: 1,
        maxHp: Number.MIN_VALUE,
        reload: 1.0,
        multi: [3, 3, 3, 3, 3, 3, 3, 3, 3],
        clumps: false,
        splitMultiDamage: true,
        deathSummonType: "hornet",
        deathSummonRarityOffset: -1,
        deathSummonFaction: "owner",
        deathSummonBehavior: "hostile"
    },
    georgeEgg: {
        id: "georgeEgg",
        label: "Yellow Hat",
        dmg: 1,
        maxHp: Number.MIN_VALUE,
        reload: 1.0,
        multi: [8, 8, 8, 8, 8, 8, 8, 8, 8],
        clumps: false,
        splitMultiDamage: true,
        deathSummonType: "george",
        deathSummonRarityOffset: -1,
        deathSummonFaction: "owner",
        deathSummonBehavior: "hostile"
    },
    bubble: {
        id: "bubble",
        label: "Bubble",
        dmg: 0,
        maxHp: 1,
        reload: 1,

        // R0 = 3s, R1 = 1.5s, R2 = 0.75s, etc.
        reloadScaling: [2, 1.75, 1.5, 1.25, 1, 0.75, 0.5, 0.25, 0],
        secondaryReload: [0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.1, 0.1],

        // Do not multiply HP by rarity scaling.
        fixedMaxHp: true,

        // Mobs cannot damage it. Used to be true, but that just made it op.
        immuneToMobDamage: false,

        // Right click pop movement.
        rightClickPop: true,
        popImpulse: 460,
        popImpulsePerRarity: 15,

        radius: 1.1
    },
    cactus: {
        id: "cactus",
        label: "Cactus",
        dmg: 10,
        maxHp: 10,
        reload: 2.5,
        radius: 1.0,

        // Applies while equipped, even if reloading/dead.
        maxHpBonus: 30,
        maxHpBonusPerRarity: 25
    },
    bloodSacrifice: {
        id: "bloodSacrifice",
        label: "Blood Sacrifice",

        dmg: 0,
        maxHp: 1,
        reload: 0,

        noPetalBody: true,
        mutli: [0, 0, 0, 0, 0, 0, 0, 0],

        deathMobRarity: 7,
        minZoneRarity: 3.5
    },
    antennae: {
        id: "antennae",
        label: "Antennae",

        dmg: 0,
        maxHp: 0,
        reload: 0,
        noPetalBody: true,
        mutli: [0, 0, 0, 0, 0, 0, 0, 0],
        unstackable: true
    },
    god: {
        id: "god",
        label: "God",
        dmg: 10000000000000,
        maxHp: 10000000000000,
        reload: 0.05,
        maxHpBonus: 1000,
        playerSpeed: 5,
    }
};

const FACTION = { NEUTRAL: 0, PLAYER: 1, ANT: 2, BEE: 3, MECH: 4, GARBAGE_BASE: 100 };

const MOB = {
    radius: 18
};

const sizeScaling = [1, 1.2, 1.5, 1.9, 3, 5, 8, 13, 21];
const hpScaling = [1, 3.75, 13.5, 54, 405, 2430, 109350, 3280500, 98415000];

const MobTypes = {
    lovebug: {
        id: "lovebug",
        label: "Lovebug",
        radius: 14,
        dmg: 6,
        maxHp: 35,
        speed: 205,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wanderSine",
        mass: 0.35,
        drops: ["rose", "light"],

        // mating behavior
        canMate: true,
        mateRange: 46,
        mateCooldown: 18,
        mateWarmup: 1.25,
        mateMaxChildrenNearby: 8,
        mateChildType: "lovebugBaby"
    },
    lovebugBaby: {
        id: "lovebugBaby",
        label: "Baby Lovebug",
        radius: 8,
        dmg: 3,
        maxHp: 12,
        speed: 225,
        behavior: "passive",
        aggroType: "none",
        idleType: "wanderSine",
        mass: 0.12,
        drops: ["rose"]
    },
    ant: {
        id: "ant",
        label: "Ant",
        radius: 10,
        dmg: 10,
        maxHp: 50,
        speed: 220,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        drops: ["leaf"],
        mass: 0.1,
    },
    antGuard: {
        id: "antGuard",
        label: "Male Ant",
        radius: 10,
        dmg: 10,
        maxHp: 50,
        speed: 220,
        aggroRange: 225,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        drops: ["glass", "faster"],
        mass: 0.1,
    },
    stinkbug: {
        id: "stinkbug",
        label: "Stinkbug",
        radius: 20,
        dmg: 12.5,
        maxHp: 45,
        speed: 241,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        drops: ["rice", "rose"],
        mass: 0.1,
    },
    demon: {
        id: "demon",
        label: "Demon",
        radius: 35,
        dmg: 50,
        maxHp: 100,
        speed: 400,
        aggroRange: 500,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        drops: ["stinger"],
        mass: 5.25,
    },
    antBaby: {
        id: "antBaby",
        label: "Baby Ant",
        radius: 10,
        dmg: 5,
        maxHp: 25,
        speed: 220,
        behavior: "passive",
        aggroType: "chase",
        idleType: "wander",
        drops: ["rice", "leaf"],
        mass: 0.1,
    },
    queenAnt: {
        id: "queenAnt",
        label: "Queen Ant",
        radius: 15,
        dmg: 10,
        maxHp: 50,
        speed: 220,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 250,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    antEgg: {
        id: "antEgg",
        label: "Ant Egg",
        radius: 15,
        dmg: 3,
        maxHp: 150,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rice", "rose"],
        mass: 5,
    },
    antHole: {
        id: "antHole",
        label: "Ant Hole",
        radius: 22,
        dmg: 6,
        maxHp: 220,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rice", "rock"],
        mass: 1e18,
        spawnAntsEveryHpFrac: 0.15,
        spawnAntsPerThreshold: 3,
        spawnAntType: "ant",
        spawnAntMinRarityDrop: 1,
        spawnAntMaxRarityDrop: 2,
        deathSpawnType: "queenAnt"
    },
    rock: {
        id: "rockMob",
        label: "Rock",
        radius: 15,
        dmg: 10,
        maxHp: 100,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rock"],
        mass: 10,
        sizeVary: true,
    },
    bubble: {
        id: "bubble",
        label: "Bubble",
        radius: 25,
        dmg: 3,
        maxHp: 0.1,
        speed: 10,
        behavior: "passive",
        aggroType: "none",
        idleType: "wander",
        drops: ["bubble"],
        mass: 10,
        sizeVary: true,
    },
    stalagmite: {
        id: "stalagmite",
        label: "Stalagmite",
        radius: 15,
        dmg: 10,
        maxHp: 25,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rock"],
        mass: 10,
        sizeVary: true,
    },
    fleshPillar: {
        id: "fleshPillar",
        label: "Flesh Pillar",
        radius: 25,
        dmg: 30,
        maxHp: 250,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["sawblade"],
        mass: 10,
        sizeVary: true,
    },
    sponge: {
        id: "sponge",
        label: "Sponge",
        radius: 25,
        dmg: 10,
        maxHp: 100,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rose"],
        mass: 30,
        sizeVary: true,
    },
    garbage: {
        id: "garbage",
        label: "Garbage",
        radius: 30,
        dmg: 3,
        maxHp: 250,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        mass: 1,
        drops: ["rock"]
    },
    sandstorm: {
        id: "sandstorm",
        label: "Sandstorm",
        radius: 35,
        dmg: 25,
        maxHp: 125,
        speed: 220,
        behavior: "passive",
        aggroType: "chase",
        idleType: "wanderSine",
        drops: ["sand"],
        mass: 0.1,
        sizeVary: true,
    },
    cactus: {
        id: "cactus",
        label: "Cactus",
        radius: 25,
        dmg: 40,
        maxHp: 50,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rose", "cactus"],
        mass: 1,
        sizeVary: true,
    },
    beetle: {
        id: "beetle",
        label: "Beetle",
        radius: 18,
        dmg: 15,
        maxHp: 100,
        speed: 225,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 170,
        mass: 0.5,
        drops: ["rock", "rose", "beetleEgg"]
    },
    mechaBeetle: {
        id: "mechaBeetle",
        label: "Beetle",
        radius: 18,
        dmg: 15,
        maxHp: 100,
        speed: 225,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 170,
        mass: 0.5,
        drops: ["rock", "rose"],
        faction: FACTION.MECH
    },
    mechaAnt: {
        id: "mechaAnt",
        label: "Termite",
        radius: 10,
        dmg: 10,
        maxHp: 100,
        speed: 260,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 300,
        mass: 3,
        drops: ["rock"],
        faction: FACTION.MECH
    },
    beetle_hel: {
        id: "beetle_hel",
        label: "Beetle",
        radius: 18,
        dmg: 30,
        maxHp: 120,
        speed: 235,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 170,
        mass: 0.71,
        drops: ["rock", "rose"]
    },
    ladybug: {
        id: "ladybug",
        label: "Ladybug",
        radius: 18,
        dmg: 10,
        maxHp: 25,
        speed: 220,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        mass: 0.5,
        drops: ["light", "rose", "yinYang"]
    },
    aphid: {
        id: "aphid",
        label: "Aphid",
        radius: 10,
        dmg: 20,
        maxHp: 70,
        speed: 220,
        behavior: "neutral",
        aggroType: "shootMissile",
        idleType: "wander",
        mass: 0.5,
        drops: ["sap"]
    },
    crab: {
        id: "crab",
        label: "Crab",
        radius: 18,
        dmg: 25,
        maxHp: 55,
        speed: 220,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wanderSine",
        aggroRange: 170,
        mass: 1,
        drops: ["rose"]
    },
    mite: {
        id: "mite",
        label: "Mite",
        radius: 10,
        dmg: 20,
        maxHp: 15,
        speed: 251,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        mass: 0.5,
        drops: ["rice", "rose"]
    },
    ladybugShiny: {
        id: "ladybugShiny",
        label: "Ladybug",
        radius: 18,
        dmg: 10,
        maxHp: 30,
        speed: 220,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        mass: 0.5,
        drops: ["rice", "rose"]
    },
    centipede: {
        id: "centipede",
        label: "Centipede",
        radius: 20,
        dmg: 8,
        maxHp: 18,
        speed: 200,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        drops: ["leaf"],
        mass: 0.5,
        length: 10
    },
    centipede_hel: {
        id: "centipede_hel",
        label: "Centipede",
        radius: 20,
        dmg: 30,
        maxHp: 50,
        speed: 400,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 200,
        drops: ["leaf"],
        mass: 0.5,
        length: 12,
        sizeVary: true,
    },
    centipedeDesert: {
        id: "centipedeDesert",
        label: "Centipede",
        radius: 20,
        dmg: 8,
        maxHp: 18,
        speed: 400,
        behavior: "neutral",
        aggroType: "chaseSine",
        idleType: "wanderSineFast",
        drops: ["sand", "faster"],
        mass: 0.5,
        length: 10
    },
    milipede: {
        id: "milipede",
        label: "Millipede",
        radius: 10,
        dmg: 10,
        maxHp: 18,
        speed: 250,
        behavior: "hostile",
        aggroType: "chaseSine",
        idleType: "wander",
        drops: ["rice", "rock"],
        mass: 0.5
    },
    hornet: {
        id: "hornet",
        label: "Hornet",
        radius: 18,
        dmg: 20,
        maxHp: 55,
        speed: 232.5,
        behavior: "hostile",
        aggroType: "shootMissile",
        idleType: "wander",
        aggroRange: 200,
        drops: ["missile", "hornetEgg", "antennae"],
        mass: 0.5,
    },
    jellyfish: {
        id: "jellyfish",
        label: "Jellyfish",
        radius: 25,
        dmg: 25,
        maxHp: 150,
        speed: 50,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wanderSineSlow",
        aggroRange: 300,
        drops: ["rice", "rose", "landmine"],
        mass: 0.15,
        lightning: {
            cooldownByRarity: [3.33, 3.33, 3.33, 2.89, 2.89, 2.89, 2.44, 2.44, 2.44],
            bouncesByRarity: [2, 2, 3, 3, 4, 4, 5, 5, 6],
            range: 125,
            damage: 15
        }
    },
    george: {
        id: "george",
        label: "George",
        radius: 45,
        dmg: 67,
        maxHp: 670,
        speed: 670,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 670,
        drops: ["landmine", "georgeEgg"],
        mass: 6.7,
    },
    antTrooper: {
        id: "antTrooper",
        label: "Ant Trooper",
        radius: 10,
        dmg: 67,
        maxHp: 670,
        speed: 670,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 670,
        drops: ["landmine", "georgeEgg"],
        mass: 6.7,
    },
    wasp: {
        id: "wasp",
        label: "Wasp",
        radius: 18,
        dmg: 20,
        maxHp: 55,
        speed: 232.5,
        behavior: "hostile",
        aggroType: "shootMissile",
        idleType: "wander",
        aggroRange: 200,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    wasp_hel: {
        id: "wasp_hel",
        label: "Wasp",
        radius: 18,
        dmg: 20,
        maxHp: 100,
        speed: 260,
        behavior: "hostile",
        aggroType: "shootMissileChasing",
        idleType: "wander",
        aggroRange: 500,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    mechaWasp: {
        id: "mechaWasp",
        label: "Wasp",
        radius: 18,
        dmg: 20,
        maxHp: 55,
        speed: 232.5,
        behavior: "hostile",
        aggroType: "shootMissile",
        idleType: "wander",
        aggroRange: 200,
        drops: ["rice", "rose"],
        mass: 0.5,
        faction: FACTION.MECH
    },
    stonefly: {
        id: "stonefly",
        label: "Stonefly",
        radius: 10,
        dmg: 10,
        maxHp: 45,
        speed: 210,
        behavior: "hostile",
        aggroType: "shootMissileChasing",
        idleType: "wander",
        aggroRange: 200,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    bee: {
        id: "bee",
        label: "Bee",
        radius: 15,
        dmg: 20,
        maxHp: 55,
        speed: 250,
        behavior: "neutral",
        aggroType: "chaseSine",
        idleType: "wanderSineSlow",
        drops: ["stinger", "pollen"],
        mass: 0.35,
    },
    elephant: {
        id: "elephant",
        label: "Elephant",
        radius: 35,
        dmg: 38,
        maxHp: 320,
        speed: 130,
        behavior: "neutral",
        aggroType: "chaseRapidClose",
        idleType: "wander",
        aggroRange: 260,
        mass: 4,
        drops: ["rice", "rock"],
        aiTurnSharpness: 10,
        aiAccelSharpness: 8,
        stompDamageMult: 1.4,
        stompRange: 80,
        stompCd: 3.0
    },
    beeEgg: {
        id: "beeEgg",
        label: "Bee Egg",
        radius: 20,
        dmg: 5,
        maxHp: 200,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    beeQueen: {
        id: "beeQueen",
        label: "Queen Bee",
        radius: 20,
        dmg: 20,
        maxHp: 150,
        speed: 250,
        behavior: "hostile",
        aggroType: "chaseSine",
        aggroRange: 250,
        drops: ["rice", "rose"],
        mass: 1.5,
    },
    bumblebee: {
        id: "bumblebee",
        label: "Bumblebee",
        radius: 15,
        dmg: 20,
        maxHp: 55,
        speed: 220,
        behavior: "hostile",
        aggroType: "shootMissilePredictive",
        idleType: "wanderSine",
        aggroRange: 250,
        drops: ["pollen", "missile"],
        mass: 0.5,
    },
    scorpion: {
        id: "scorpion",
        label: "Scorpion",
        radius: 20,
        dmg: 15,
        maxHp: 75,
        speed: 200,
        behavior: "hostile",
        aggroType: "chaseRapidClose",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.5,
        drops: ["rice", "rose", "pincer"]
    },
    starfish: {
        id: "starfish",
        label: "Starfish",
        radius: 20.75,
        dmg: 20,
        maxHp: 50,
        speed: 220,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "spin",
        aggroRange: 250,
        mass: 0.5,
        drops: ["rice", "rose", "pincer"]
    },
    pillbug: {
        id: "pillbug",
        label: "Pill Bug",
        radius: 21,
        dmg: 35,
        maxHp: 75,
        speed: 200,
        behavior: "hostile",
        aggroType: "chaseRapidClose",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.5,
        drops: ["rice", "rose"]
    },
    fly: {
        id: "fly",
        label: "Fly",
        radius: 10,
        dmg: 5,
        maxHp: 5,
        speed: 230,
        behavior: "hostile",
        aggroType: "chaseSine",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.05,
        drops: ["rice", "rose", "poo"]
    },
    silverfish: {
        id: "silverfish",
        label: "Silverfish",
        radius: 15,
        dmg: 8,
        maxHp: 20,
        speed: 255,
        behavior: "hostile",
        aggroType: "silverfishScavenge",
        idleType: "wander",
        aggroRange: 240,
        mass: 0.08,
        drops: ["rice", "rock"]
    },
    mosquito: {
        id: "mosquito",
        label: "Mosquito",
        radius: 10,
        dmg: 5,
        maxHp: 5,
        speed: 230,
        behavior: "hostile",
        aggroType: "chaseSine",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.05,
        drops: ["faster"]
    },
    spider: {
        id: "spider",
        label: "Tarantula",
        radius: 10,
        dmg: 15,
        maxHp: 35,
        speed: 220,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 250,
        mass: 0.05,
        drops: ["faster"]
    },
    clam: {
        id: "clam",
        label: "Clam",
        radius: 16,
        dmg: 15,
        maxHp: 50,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        mass: 1.5,
        drops: ["rice", "rose"]
    },
    leech: {
        id: "leech",
        label: "Leech",
        radius: 7,
        dmg: 2,
        maxHp: 100,
        speed: 300,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wanderSine",
        aggroRange: 230,
        mass: 0.35,
        drops: ["rice", "rose"],

        // Rope-link body config.
        ropeBody: true,
        bodySegments: 14,
        bodySegmentRadiusMult: 0.82,
        bodySegmentSpacingMult: 1.15,
        bodyFollowSharpness: 16
    },
    dandelion: {
        id: "dandelion",
        label: "Dandelion",
        radius: 21,
        dmg: 15,
        maxHp: 100,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        mass: 2,
        drops: ["rice", "rose"]
    }
};

const MobObjectTypes = {
    hornetMissile: {
        id: "hornetMissile",
        label: "Stinger",
        baseDmg: 5,
        baseHp: 12,
        radius: 10,
        speed: 400,
        life: 100,
        homing: false,
        turnRate: 8.0
    },
    dandelionMissile: {
        id: "dandelionMissile",
        label: "Seed",
        baseDmg: 15,
        baseHp: 15,
        radius: 7,
        speed: 300,
        life: 2.5,
        homing: false,
        turnRate: 0
    }
};

module.exports = {
    PETAL,
    PETAL_RARITY,
    PETAL_RARITY_SCALE,
    PetalTypes,
    FACTION,
    MOB,
    sizeScaling,
    hpScaling,
    MobTypes,
    MobObjectTypes
};
