"use strict";

const PETAL = {
    count: 10,
    orbitSpeed: 2.4,
    radius: 7.5,
    subpetalRadius: 7.5
};

const PETAL_RARITY = {
    min: 0,
    max: 8
};

const PETAL_RARITY_SCALE = [
    0,    // rarity 0 Common
    3,    // rarity 1 Uncommon
    9,    // rarity 2
    27,   // rarity 3
    81,   // rarity 4
    243,  // rarity 5
    729,  // rarity 6
    2187, // rarity 7
    6561  // rarity 8
];

const PetalTypes = {
    basic: { id: "basic", label: "Basic", dmg: 10, maxHp: 10, reload: 2.0 },
    rose: { id: "rose", label: "Rose", dmg: 5, maxHp: 10, reload: 2.0, heal: 5, healCooldown: 0.5, radius: .75 },
    rock: { id: "rock", label: "Rock", dmg: 5, maxHp: 15, reload: 3.0, radius: 1.1 },
    rice: { id: "rice", label: "Rice", dmg: 5, maxHp: 1, reload: 0.000001, radius: .55, },
    stinger: { id: "stinger", label: "Stinger", dmg: 100, maxHp: 5, reload: 5, radius: .55, multi: [1, 1, 1, 1, 1, 3, 5, 5, 6], clumps: true, splitMultiDamage: true, },
    poo: { id: "poo", label: "Poo", dmg: 1, maxHp: 8, reload: 4.0, aggroRangeMult: 0.10 },
    lentil: { id: "lentil", label: "Lentil", dmg: 12, maxHp: 15, reload: 4.0, petalAttractBonus: 0.007, radius: .45 },
    landmine: {
        id: "landmine",
        label: "Landmine",
        dmg: 100,
        maxHp: 10,
        reload: 5.0,
        isDroppable: true,
        explosionRadiusBase: 500,
        explosionRadiusScale: 1.2, radius: 1.15
    },
    light: {
        id: "light",
        label: "Light",
        dmg: 12,
        maxHp: 8,
        reload: 0.75,
        multi: [1, 1, 2, 2, 3, 3, 4, 4, 5],
        clumps: false,
        splitMultiDamage: true,
        sizeRatio: 0.75,
    },
    yinYang: {
        id: "yinYang",
        label: "Yin Yang",
        dmg: 10,
        maxHp: 10,
        reload: 2.5,
        reversePetalRotation: true
    },
    pincer: {
        id: "pincer",
        label: "Pincer",
        dmg: 7,
        maxHp: 12,
        reload: 2.5,
        slowAmount: 0.25,
        slowDuration: 2.0,
        slowDurationPerRarity: 0.35
    },
    sawblade: {
        id: "sawblade",
        label: "Sawblade",
        dmg: 40,
        maxHp: 25,
        reload: 2.0
    },
    beetleEgg: {
        id: "beetleEgg",
        label: "Beetle Egg",
        dmg: 1,
        maxHp: Number.MIN_VALUE,
        reload: 1.0,
        deathSummonType: "beetle",
        deathSummonRarityOffset: -1,
        deathSummonFaction: "owner",
        deathSummonBehavior: "hostile"
    },
    antEgg: {
        id: "antEgg",
        label: "Ant Egg",
        dmg: 1,
        maxHp: Number.MIN_VALUE,
        reload: 1.0,
        deathSummonType: "antGuard",
        deathSummonRarityOffset: -1,
        deathSummonFaction: "owner",
        deathSummonBehavior: "hostile"
    },
    god: {
        id: "god",
        label: "God",
        dmg: 10000000000000,
        maxHp: 10000000000000,
        reload: 0.05
    }
};

const FACTION = { NEUTRAL: 0, PLAYER: 1, ANT: 2, BEE: 3, MECH: 4, GARBAGE_BASE: 100 };

const MOB = {
    radius: 18
};

const sizeScaling = [1, 1.2, 1.5, 1.9, 3, 5, 8, 13, 21];
const hpScaling = [1, 3.75, 13.5, 54, 405, 2430, 109350, 3280500, 98415000];

const MobTypes = {
    lovebug: {
        id: "lovebug",
        label: "Lovebug",
        radius: 14,
        dmg: 6,
        maxHp: 35,
        speed: 205,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wanderSine",
        mass: 0.35,
        drops: ["rose", "light"],

        // mating behavior
        canMate: true,
        mateRange: 46,
        mateCooldown: 18,
        mateWarmup: 1.25,
        mateMaxChildrenNearby: 8,
        mateChildType: "lovebugBaby"
    },

    lovebugBaby: {
        id: "lovebugBaby",
        label: "Baby Lovebug",
        radius: 8,
        dmg: 3,
        maxHp: 12,
        speed: 225,
        behavior: "passive",
        aggroType: "none",
        idleType: "wanderSine",
        mass: 0.12,
        drops: ["rose"]
    },
    ant: {
        id: "ant",
        label: "Ant",
        radius: 10,
        dmg: 10,
        maxHp: 50,
        speed: 221,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        drops: ["rice", "rose"],
        mass: 0.1,
    },
    antGuard: {
        id: "antGuard",
        label: "Male Ant",
        radius: 10,
        dmg: 10,
        maxHp: 50,
        speed: 221,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        drops: ["rice", "rose"],
        mass: 0.1,
    },
    stinkbug: {
        id: "stinkbug",
        label: "Stinkbug",
        radius: 20,
        dmg: 12.5,
        maxHp: 45,
        speed: 241,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        drops: ["rice", "rose"],
        mass: 0.1,
    },
    antBaby: {
        id: "antBaby",
        label: "Baby Ant",
        radius: 10,
        dmg: 5,
        maxHp: 25,
        speed: 221,
        behavior: "passive",
        aggroType: "chase",
        idleType: "wander",
        drops: ["rice", "rock"],
        mass: 0.1,
    },
    queenAnt: {
        id: "queenAnt",
        label: "Queen Ant",
        radius: 15,
        dmg: 10,
        maxHp: 50,
        speed: 221,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 250,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    antEgg: {
        id: "antEgg",
        label: "Ant Egg",
        radius: 15,
        dmg: 3,
        maxHp: 150,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rice", "rose"],
        mass: 5,
    },
    antHole: {
        id: "antHole",
        label: "Ant Hole",
        radius: 22,
        dmg: 6,
        maxHp: 220,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rice", "rock"],
        mass: 1e18,
        spawnAntsEveryHpFrac: 0.15,
        spawnAntsPerThreshold: 3,
        spawnAntType: "ant",
        spawnAntMinRarityDrop: 1,
        spawnAntMaxRarityDrop: 2,
        deathSpawnType: "queenAnt"
    },
    rock: {
        id: "rockMob",
        label: "Rock",
        radius: 15,
        dmg: 10,
        maxHp: 100,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rock"],
        mass: 10,
        sizeVary: true,
    },
    bubble: {
        id: "bubble",
        label: "Bubble",
        radius: 25,
        dmg: 3,
        maxHp: 0.1,
        speed: 10,
        behavior: "passive",
        aggroType: "none",
        idleType: "wander",
        drops: ["rose"],
        mass: 10,
        sizeVary: true,
    },
    stalagmite: {
        id: "stalagmite",
        label: "Stalagmite",
        radius: 15,
        dmg: 10,
        maxHp: 25,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rock"],
        mass: 10,
        sizeVary: true,
    },
    garbage: {
        id: "garbage",
        label: "Garbage",
        radius: 30,
        dmg: 3,
        maxHp: 250,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        mass: 1,
        drops: ["rock"]
    },
    sandstorm: {
        id: "sandstorm",
        label: "Sandstorm",
        radius: 35,
        dmg: 25,
        maxHp: 125,
        speed: 221,
        behavior: "passive",
        aggroType: "chase",
        idleType: "wanderSine",
        drops: ["rice", "rock"],
        mass: 0.1,
        sizeVary: true,
    },
    cactus: {
        id: "cactus",
        label: "Cactus",
        radius: 25,
        dmg: 40,
        maxHp: 50,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rose"],
        mass: 1,
        sizeVary: true,
    },
    beetle: {
        id: "beetle",
        label: "Beetle",
        radius: 18,
        dmg: 15,
        maxHp: 100,
        speed: 225,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 170,
        mass: 0.5,
        drops: ["rock", "rose", "beetleEgg"]
    },
    mechaBeetle: {
        id: "mechaBeetle",
        label: "Beetle",
        radius: 18,
        dmg: 15,
        maxHp: 100,
        speed: 225,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 170,
        mass: 0.5,
        drops: ["rock", "rose"],
        faction: FACTION.MECH
    },
    mechaAnt: {
        id: "mechaAnt",
        label: "Termite",
        radius: 10,
        dmg: 10,
        maxHp: 100,
        speed: 260,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 300,
        mass: 3,
        drops: ["rock"],
        faction: FACTION.MECH
    },
    beetle_hel: {
        id: "beetle_hel",
        label: "Beetle",
        radius: 18,
        dmg: 30,
        maxHp: 120,
        speed: 235,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 170,
        mass: 0.71,
        drops: ["rock", "rose"]
    },
    ladybug: {
        id: "ladybug",
        label: "Ladybug",
        radius: 18,
        dmg: 10,
        maxHp: 25,
        speed: 221,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        mass: 0.5,
        drops: ["light", "rose", "yinYang"]
    },
    crab: {
        id: "crab",
        label: "Crab",
        radius: 18,
        dmg: 25,
        maxHp: 55,
        speed: 221,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wanderSine",
        aggroRange: 170,
        mass: 1,
        drops: ["rose"]
    },
    mite: {
        id: "mite",
        label: "Mite",
        radius: 10,
        dmg: 20,
        maxHp: 15,
        speed: 251,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        mass: 0.5,
        drops: ["rice", "rose"]
    },
    ladybugShiny: {
        id: "ladybugShiny",
        label: "Ladybug",
        radius: 18,
        dmg: 10,
        maxHp: 30,
        speed: 221,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        mass: 0.5,
        drops: ["rice", "rose"]
    },
    centipede: {
        id: "centipede",
        label: "Centipede",
        radius: 20,
        dmg: 8,
        maxHp: 18,
        speed: 200,
        behavior: "neutral",
        aggroType: "chase",
        idleType: "wander",
        drops: ["rice", "rock"],
        mass: 0.5,
        length: 10
    },
    centipedeDesert: {
        id: "centipedeDesert",
        label: "Centipede",
        radius: 20,
        dmg: 8,
        maxHp: 18,
        speed: 400,
        behavior: "neutral",
        aggroType: "chaseSine",
        idleType: "wanderSine",
        drops: ["rice", "rock"],
        mass: 0.5,
        length: 10
    },
    milipede: {
        id: "milipede",
        label: "Millipede",
        radius: 10,
        dmg: 10,
        maxHp: 18,
        speed: 250,
        behavior: "hostile",
        aggroType: "chaseSine",
        idleType: "wander",
        drops: ["rice", "rock"],
        mass: 0.5
    },
    hornet: {
        id: "hornet",
        label: "Hornet",
        radius: 18,
        dmg: 20,
        maxHp: 55,
        speed: 232.5,
        behavior: "hostile",
        aggroType: "shootMissile",
        idleType: "wander",
        aggroRange: 200,
        drops: ["rice", "rose", "landmine"],
        mass: 0.5,
    },
    jellyfish: {
        id: "jellyfish",
        label: "Jellyfish",
        radius: 25,
        dmg: 25,
        maxHp: 150,
        speed: 200,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wanderSine",
        aggroRange: 300,
        drops: ["rice", "rose", "landmine"],
        mass: 0.15,
        lightning: {
            cooldownByRarity: [3.33, 3.33, 3.33, 2.89, 2.89, 2.89, 2.44, 2.44, 2.44],
            bouncesByRarity: [2, 2, 3, 3, 4, 4, 5, 5, 6],
            range: 125,
            damage: 15
        }
    },
    george: {
        id: "george",
        label: "George",
        radius: 45,
        dmg: 67,
        maxHp: 670,
        speed: 670,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 670,
        drops: ["landmine"],
        mass: 6.7,
    },
    wasp: {
        id: "wasp",
        label: "Wasp",
        radius: 18,
        dmg: 20,
        maxHp: 55,
        speed: 232.5,
        behavior: "hostile",
        aggroType: "shootMissile",
        idleType: "wander",
        aggroRange: 200,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    mechaWasp: {
        id: "mechaWasp",
        label: "Wasp",
        radius: 18,
        dmg: 20,
        maxHp: 55,
        speed: 232.5,
        behavior: "hostile",
        aggroType: "shootMissile",
        idleType: "wander",
        aggroRange: 200,
        drops: ["rice", "rose"],
        mass: 0.5,
        faction: FACTION.MECH
    },
    stonefly: {
        id: "stonefly",
        label: "Stonefly",
        radius: 10,
        dmg: 10,
        maxHp: 45,
        speed: 210,
        behavior: "hostile",
        aggroType: "shootMissileChasing",
        idleType: "wander",
        aggroRange: 200,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    bee: {
        id: "bee",
        label: "Bee",
        radius: 15,
        dmg: 20,
        maxHp: 55,
        speed: 250,
        behavior: "neutral",
        aggroType: "chaseSine",
        idleType: "wanderSine",
        drops: ["stinger"],
        mass: 0.35,
    },
    beeEgg: {
        id: "beeEgg",
        label: "Bee Egg",
        radius: 20,
        dmg: 5,
        maxHp: 200,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    beeQueen: {
        id: "beeQueen",
        label: "Queen Bee",
        radius: 20,
        dmg: 20,
        maxHp: 150,
        speed: 250,
        behavior: "hostile",
        aggroType: "chaseSine",
        aggroRange: 250,
        drops: ["rice", "rose"],
        mass: 1.5,
    },
    bumblebee: {
        id: "bumblebee",
        label: "Bumblebee",
        radius: 15,
        dmg: 20,
        maxHp: 55,
        speed: 221,
        behavior: "hostile",
        aggroType: "shootMissilePredictive",
        idleType: "wanderSine",
        aggroRange: 250,
        drops: ["rice", "rose"],
        mass: 0.5,
    },
    scorpion: {
        id: "scorpion",
        label: "Scorpion",
        radius: 20,
        dmg: 15,
        maxHp: 75,
        speed: 200,
        behavior: "hostile",
        aggroType: "chaseRapidClose",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.5,
        drops: ["rice", "rose", "pincer"]
    },
    pillbug: {
        id: "pillbug",
        label: "Pill Bug",
        radius: 21,
        dmg: 35,
        maxHp: 75,
        speed: 200,
        behavior: "hostile",
        aggroType: "chaseRapidClose",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.5,
        drops: ["rice", "rose"]
    },
    fly: {
        id: "fly",
        label: "Fly",
        radius: 10,
        dmg: 5,
        maxHp: 5,
        speed: 230,
        behavior: "hostile",
        aggroType: "chaseSine",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.05,
        drops: ["rice", "rose", "poo"]
    },
    silverfish: {
        id: "silverfish",
        label: "Silverfish",
        radius: 15,
        dmg: 8,
        maxHp: 20,
        speed: 255,
        behavior: "hostile",
        aggroType: "silverfishScavenge",
        idleType: "wander",
        aggroRange: 240,
        mass: 0.08,
        drops: ["rice", "rock"]
    },
    mosquito: {
        id: "mosquito",
        label: "Mosquito",
        radius: 10,
        dmg: 5,
        maxHp: 5,
        speed: 230,
        behavior: "hostile",
        aggroType: "chaseSine",
        idleType: "wanderSine",
        aggroRange: 250,
        mass: 0.05,
        drops: ["rice", "rose"]
    },
    spider: {
        id: "spider",
        label: "Tarantula",
        radius: 10,
        dmg: 15,
        maxHp: 35,
        speed: 221,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wander",
        aggroRange: 250,
        mass: 0.05,
        drops: ["rice", "rose"]
    },
    clam: {
        id: "clam",
        label: "Clam",
        radius: 16,
        dmg: 15,
        maxHp: 50,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        mass: 1.5,
        drops: ["rice", "rose"]
    },
    leech: {
        id: "leech",
        label: "Leech",
        radius: 7,
        dmg: 2,
        maxHp: 100,
        speed: 300,
        behavior: "hostile",
        aggroType: "chase",
        idleType: "wanderSine",
        aggroRange: 230,
        mass: 0.35,
        drops: ["rice", "rose"],

        // Rope-link body config.
        ropeBody: true,
        bodySegments: 14,
        bodySegmentRadiusMult: 0.82,
        bodySegmentSpacingMult: 1.15,
        bodyFollowSharpness: 16
    },
    dandelion: {
        id: "dandelion",
        label: "Dandelion",
        radius: 21,
        dmg: 15,
        maxHp: 100,
        speed: 0,
        behavior: "passive",
        aggroType: "none",
        idleType: "none",
        mass: 2,
        drops: ["rice", "rose"]
    }
};

const MobObjectTypes = {
    hornetMissile: {
        id: "hornetMissile",
        label: "Stinger",
        baseDmg: 5,
        baseHp: 12,
        radius: 6,
        speed: 400,
        life: 100,
        homing: false,
        turnRate: 8.0
    },
    dandelionMissile: {
        id: "dandelionMissile",
        label: "Seed",
        baseDmg: 15,
        baseHp: 15,
        radius: 7,
        speed: 300,
        life: 2.5,
        homing: false,
        turnRate: 0
    }
};

module.exports = {
    PETAL,
    PETAL_RARITY,
    PETAL_RARITY_SCALE,
    PetalTypes,
    FACTION,
    MOB,
    sizeScaling,
    hpScaling,
    MobTypes,
    MobObjectTypes
};
